horizon: 20
simulation time: 200
simulation runs: 2
simulation patience: 5
control init: 

distance cost: 1
angle cost: 1
collision cost: 20
collision radius: 5
obstacle cost: 20
obstacle radius: 5
smoothness cost: 0.1 
travel dist cost: 0

position tolerance: 1.0
angle tolerance: 0.2
stop tolerance: 0.05

figure size: 8
figure limit: 30
ticks step: 5
car size: 
  - 1.0
  - 2.5
num of vehicles: 
num of obstacles: 

data folder: ./data/prediction
model path: ./models/IterGNN_UAttentionConv.pth

convolution type: UAttentionConv # UAttentionConv, TransformerConv, EdgeConv, GAINet 
                                 # or {$Network_Arch$}_NoVehicleEdges (for the test of step efficiency)

plot folder: ./plots/prediction
show plot: False
save plot: True 

show optimization: False
random offset: False 

collision mode: True # higher priority than parking mode
parking mode: False

collect data: True, 
collect trajectory: True

test data souce: on the fly # fixed test data, on the fly
test data folder: ./data/test_dataset
test data each case:

problem collection: # [num of vehicle, num of obstacle]
  - [1, 0]
  - [1, 1]
  - [1, 2]
  - [1, 3]
  - [1, 4]
  - [2, 0]
  - [2, 1]
  - [2, 2]
  - [2, 3]
  - [2, 4]
  - [3, 0]
  - [3, 1]
  - [3, 2]
  - [3, 3]
  - [3, 4]
  - [4, 0]
  - [4, 1]
  - [4, 2]
  - [4, 3]
  - [5, 0]
  - [5, 1]
  - [5, 2]
  - [6, 0]
  - [6, 1]
  - [6, 2]
  - [6, 3]